AffineG2 introspection
aurora-is-near/aurora-bn pull request #1
Opened 2022-04-16 09:22 UTC by birchmd

The adds a few methods to be able to look at the component parts of elements of `AffineG2`. This introspection will allow us to pass the elements into NEAR's alt_bn128 pairing host function, which will soon be stabilized in nearcore.

To see how these functions are used see https://github.com/birchmd/aurora-engine/blob/794aa48a2ec4949b7af3375ecd02d2db198a0246/engine-precompiles/src/bn128.rs#L364-L383

This PR also fixes the compilation of the tests and fixes some formatting (see https://github.com/aurora-is-near/aurora-bn/commit/81ef5d670e87186f52f3bcd379d2acae3833ab38 and https://github.com/aurora-is-near/aurora-bn/commit/97d30973f71c3087b52794571ad6d783c901ce30 )

2022-06-28 08:25 UTC, RomanHodulak requested changes

2022-06-28 08:25 UTC, RomanHodulak commented on Cargo.toml
> +std = ["serde/std", "rand/std", "rand/std_rng", "byteorder/std"]
I don't think this is right. `rand/std_rng` [points to the `rand_chacha` crate](https://github.com/rust-random/rand/blob/master/Cargo.toml#L48) with [`default-features` off](https://github.com/rust-random/rand/blob/master/Cargo.toml#L69). The same crate also [claims to be `no_std` compatible](https://github.com/rust-random/rand/tree/master/rand_chacha#crate-features), having `std` feature [enabled by default](https://github.com/rust-random/rand/blob/master/rand_chacha/Cargo.toml#L27).

The `rand/std_rng` feature alone brings you only the `rand_chacha` crate and `StdRng` trait without `std`. I think `std` means two different things in the context of the `rand` crate, once as the standard library and once as a default random algorithm.

So, to turn on `std` for `rand_chacha`, you only need to [turn on `rand/std`](https://github.com/rust-random/rand/blob/master/Cargo.toml#L36). 

Perhaps we can make this feature enabled by `default`?

```toml
[features]
default = ["std", "rand", "rand/std_rng", "serde"]
```

Alternatively, if we need it all the time, simply put it to `dependencies.rand.features`.

```toml
[dependencies]
rand = { version = "0.8", default-features = false, features = ["getrandom", "rand/std_rng"], optional = true }
```

However, maybe we don't need `rand/std_rng` here altogether and we should just enable it in `aurora-test` crate of `aurora-engine`? That's what I understood from the PR description is the real purpose of this feature, to fix `aurora-test`.

2022-06-28 12:52 UTC, birchmd commented on Cargo.toml
> +std = ["serde/std", "rand/std", "rand/std_rng", "byteorder/std"]
It has nothing to do with aurora-engine. This is about fixing the tests in this crate. Run `cargo test` on the `master` branch to see the problem. If you have another solution to make the tests compile, feel free to modify this PR as you wish.

2022-06-28 18:01 UTC, RomanHodulak commented on Cargo.toml
> +std = ["serde/std", "rand/std", "rand/std_rng", "byteorder/std"]
I'll resolve this then, thanks. Sorry about the confusion with the aurora-engine, now I get it.

2022-06-30 06:49 UTC, joshuajbouw commented
Just a note, I'm still surprised that there really isn't any other up to date BN library besides others loosely keeping the old 5 year old one up to date. Would be worth a look to see the [substrate-bn](https://lib.rs/crates/substrate-bn) and similars to see if it has everything we need already.

2022-08-15 13:13 UTC, closed without merging